# Generated by Django 5.1.5 on 2025-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails_first_name_userdetails_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
    ]
