# Generated by Django 5.1.5 on 2025-02-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cover_photo',
            field=models.ImageField(blank=True, default='media/cover_photos/default_cover.png', upload_to='media/cover_photos/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://www.dreamstime.com/default-avatar-profile-icon-vector-social-media-user-image-image182145777', upload_to='media/profile_pics/'),
        ),
    ]
