# Generated by Django 5.1.5 on 2025-02-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetails_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/default_cover.png', upload_to='media/cover_photos/'),
        ),
    ]
