# Generated by Django 5.1.5 on 2025-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userdetails_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default_cover.png', upload_to='media/cover_photos/'),
        ),
    ]
