# Generated by Django 5.1.5 on 2025-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userdetails_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cover_photo',
            field=models.ImageField(blank=True, default='media/media/cover_photos/default_cover.png', upload_to='media/cover_photos/'),
        ),
    ]
