# Generated by Django 5.1.5 on 2025-02-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userdetails_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/default_cover.png', upload_to='cover_photos/'),
        ),
    ]
