# Generated by Django 5.1.5 on 2025-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userdetails_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_pfp.png', upload_to='media/profile_pics/'),
        ),
    ]
