# Generated by Django 5.1.5 on 2025-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_pfp.png', upload_to='profile_pics/'),
        ),
    ]
