# Generated by Django 5.1.5 on 2025-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='bio',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mobile_number',
            field=models.CharField(default='Not Added', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='relationship_status',
            field=models.CharField(default='Not Added', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='works_at',
            field=models.CharField(default='Not Added', max_length=100),
        ),
    ]
