# Generated by Django 5.1.5 on 2025-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_userdetails_bio_userdetails_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(default='Not Added', max_length=100),
        ),
    ]
