# Generated by Django 5.1.5 on 2025-02-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment'),
        ('user', '0015_alter_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdetails'),
        ),
    ]
