# Generated by Django 5.1.5 on 2025-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comment_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
